server:
  port: 8080

log:
  level: "info"
  json: false

database:
    host: localhost
    port: 3306
    user: tabeo_user
    name: tabeo
    password: password

cache:
  ttl: 86400
  host: localhost
  port: 6379
  db: 0

holidays:
  country: GB
  url: https://date.nager.at/api/v3/publicholidays/%d/%s